/**
 * Server-side PDF renderer for invoices.
 *
 * Architecture:
 *   The PDF is generated by Playwright (headless Chromium) navigating to the
 *   /invoices/[id]/print page, waiting for fonts and layout, then calling
 *   page.pdf(). This produces a real vector PDF with selectable text, proper
 *   Arabic shaping, crisp typography, and scannable barcodes/QR codes.
 *
 *   The browser preview (/invoices/[id]) and the PDF renderer both use the
 *   same PrintableInvoice component — there is no separate template.
 *
 * Components:
 *   - src/lib/pdf/printer.ts        Playwright browser management + PDF generation
 *   - src/app/api/invoices/[id]/pdf/route.ts   API route used by the "Download PDF" button
 *
 * To generate a PDF programmatically (e.g. for bulk or email):
 *
 *   import { renderInvoiceToPdf } from "@/components/invoice/server-pdf-renderer";
 *   const { buffer, fileName } = await renderInvoiceToPdf({
 *     url: "/invoices/abc123/print",
 *     cookies: [{ name: "session", value: "..." }],
 *   });
 */

import { generatePdfFromUrl } from "@/lib/pdf/printer";

export interface PdfRenderInput {
  url: string;
  cookies?: { name: string; value: string }[];
}

export interface PdfRenderOutput {
  buffer: Uint8Array;
  fileName: string;
}

export async function renderInvoiceToPdf(input: PdfRenderInput): Promise<PdfRenderOutput> {
  const buffer = await generatePdfFromUrl(input.url, input.cookies ?? []);
  const fileName = `invoice-${new Date().toISOString().split("T")[0]}.pdf`;
  return { buffer, fileName };
}
